key_bindings:
  - { key: J,        mods: Alt,     chars: "\x1bj"}
  - { key: K,        mods: Alt,     chars: "\x1bk"}
  - { key: H,        mods: Alt,     chars: "\x1bh"}
  - { key: L,        mods: Alt,     chars: "\x1bl"}
    # Here we add a Tab at the end in order to get tab completion with same
    # key after expanding command
  - { key: E,        mods: Control, chars: "\x1be\t"}

font:
  size: 12.0
  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

hide_cursor_when_typing: true

